DROP DATABASE IF EXISTS northwind_dw;

CREATE DATABASE northwind_dw;

USE northwind_dw;

CREATE TABLE dim_customer (
    	CUSTOMER_ID VARCHAR(5) NOT NULL,
    	COMPANY_NAME VARCHAR(40)  NOT NULL,
    	CITY VARCHAR(255),
    	COUNTRY VARCHAR(255),
    	PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE dim_product (
	PRODUCT_KEY INTEGER,
	PRODUCT_NAME varchar(70),
	PRODUCT_ID INTEGER,
	CATEGORY_NAME varchar(70),
	VERSION INT,
	DATE_FROM DATETIME,
	DATE_TO DATETIME,
 	PRIMARY KEY (PRODUCT_KEY)
);

CREATE TABLE dim_supplier (
	SUPPLIER_ID INTEGER NOT NULL,
	COMPANY_NAME VARCHAR(40),
	CITY VARCHAR(255),
    	COUNTRY VARCHAR(255),
    	PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE dim_shipper (
   	SHIPPER_ID INTEGER NOT NULL,
	COMPANY_NAME VARCHAR(40),
	PRIMARY KEY(SHIPPER_ID)
);

CREATE TABLE dim_time (
    	TIME_ID DATETIME,
    	DAY INT,
    	MONTH_ID INT,
    	MONTH_NAME VARCHAR(255),
    	YEAR INT,
    	PRIMARY KEY (TIME_ID)
);

CREATE TABLE fact_order (
	ORDER_ID INT,
	PRODUCT_KEY INT,
	CUSTOMER_ID VARCHAR(5),
	SUPPLIER_ID INT,
	SHIPPER_ID INT,
	TOTAL_PRICE DECIMAL(10, 4) NOT NULL,
	TIME_ID DATETIME,
	PRIMARY KEY (ORDER_ID, PRODUCT_KEY),
	FOREIGN KEY (PRODUCT_KEY) REFERENCES dim_product (PRODUCT_KEY),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES dim_customer (CUSTOMER_ID),
	FOREIGN KEY (SUPPLIER_ID) REFERENCES dim_supplier (SUPPLIER_ID),
	FOREIGN KEY (SHIPPER_ID) REFERENCES dim_shipper (SHIPPER_ID)
);
